import * as functions from "./files/functions.js";

import "../scss/style.scss";
import spoller from "./files/spoller.js";
import burger from "./files/burger.js";
import select from "./files/select.js";
import modal from "./files/modal.js";
import sliders from "./files/sliders.js";
import servicesSort from "./files/servicesSort.js";
import fancy from "./files/fancy.js";
import animationHero from "./files/animationHero.js";
import servicesChange from "./files/servicesChange.js";
import animationBanner from "./files/animationBanner.js";
import map from "./files/map.js";
import cart from "./files/cart.js";
import tab from "./files/tab.js";
import toggleSettingBook from "./files/toggleSettingBook.js";
import services from "./files/services.js";
import diagnostics from "./files/diagnostics.js";

functions.mediaAdaptive();
spoller();
burger();
select();
modal();
sliders();
servicesSort();
fancy();
animationHero();
servicesChange();
animationBanner();
map();
cart();
tab();
toggleSettingBook();
services();
diagnostics();